Initial project creation with simple workers and handlers
ITWDiagraph/BoxwriterInterop pull request #1
Opened 2023-02-27 19:26 UTC by Gishe

2023-02-27 19:46 UTC, Drise13 commented on Abstracts/BoxwriterWorkerBase.cs
> +    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
I think these are more commonly referred to as simply `token`

2023-02-27 19:46 UTC, Drise13 commented on Abstracts/BoxwriterWorkerBase.cs
> +        var tasks = new List<Task>();
format linting

2023-02-27 19:46 UTC, Drise13 commented on Properties/launchSettings.json
> +        "DOTNET_ENVIRONMENT": "Development"
I feel like we answered this before, but should this be `Development`?

2023-02-27 19:55 UTC, Gishe commented on TCP/BoxwriterTCPHandler.cs
> +        var response = Encoding.ASCII.GetBytes(data + " From server");
I was just tagging in some extra data so that I could confirm that it was coming back from the server with some extra data.

2023-02-27 20:00 UTC, Gishe commented on Abstracts/BoxwriterWorkerBase.cs
> +    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
This is what comes from the .net Background service https://learn.microsoft.com/en-us/dotnet/core/extensions/workers

2023-02-27 20:02 UTC, Gishe commented on Properties/launchSettings.json
> +        "DOTNET_ENVIRONMENT": "Development"
This is boiler plate from the .net worker template.

2023-02-27 20:05 UTC, Gishe commented on TCP/BoxwriterTCPWorker.cs
> +        TcpListener? server = null;
This is required otherwise the finally could happen against an uninitialized variable.

2023-02-27 20:18 UTC, Gishe commented on UDP/BoxwriterUDPHandler.cs
> +            var response = Encoding.ASCII.GetBytes($"{{Locate BoxWriter, {ipAddress}, 2202, {Dns.GetHostName()}}}");
Not sure what the question is here.  This is string interpolation using {{ to escape the single {

2023-02-27 20:44 UTC, erikgabbard requested changes

2023-02-27 20:44 UTC, erikgabbard commented on UDP/BoxwriterUDPWorker.cs
> +    private const int listenPort = 2202;
Naming rule violation: `ListenPort` and it could probably just be shortened to `Port`.

2023-02-27 20:44 UTC, erikgabbard commented on UDP/BoxwriterUDPHandler.cs
> +            var client = new UdpClient();
`UdpClient` implements `IDisposable` and should be wrapped in a `using`.

`using var client = new UdpClient();`

2023-02-27 20:44 UTC, erikgabbard commented on TCP/BoxwriterTCPHandler.cs
> +        var response = Encoding.ASCII.GetBytes(data + " From server");
Why append " From server" at all?

2023-02-27 20:44 UTC, erikgabbard commented on TCP/BoxwriterTCPWorker.cs
> +        TcpListener? server = null;
`server` should not be `nullable`.  The `TcpListener` ctor should return a valid object or throw an `ArgumentNullException` or `ArgumentOutOfRangeException` which should be explictly handled by a `catch`.

2023-02-27 20:44 UTC, erikgabbard commented on UDP/BoxwriterUDPHandler.cs
> +﻿namespace BoxwriterResmarkInterop;
Not sure I see a reason to implement separate handlers to process the data when a simple method on the worker class would suffice.  Do we intend to extend these handlers in the future?

2023-02-27 20:44 UTC, erikgabbard commented on Program.cs
> +    .ConfigureLogging(logger =>
@Gishe You touched on it in conversation, but the logger should log to a file or other durable repository in production (logging to the console is ok for development).

2023-02-27 20:44 UTC, erikgabbard commented on BoxwriterResmarkInterop.csproj
> +        <UserSecretsId>dotnet-BoxwriterResmarkInterop-6F577E19-B680-4C10-A8C8-3D8E1CA5DD75</UserSecretsId>
It looks like you have enabled `UserSecrets` but are not using them anywhere.

2023-02-27 20:44 UTC, erikgabbard commented on TCP/BoxwriterTCPHandler.cs
> +    public async Task ProcessData(string data, NetworkStream stream, CancellationToken cancellationToken = default)
Asynchronous method names should be suffixed with `Async`.

2023-02-27 20:44 UTC, erikgabbard commented on UDP/BoxwriterUDPHandler.cs
> +    public void ProcessData(UdpReceiveResult data, IPAddress ipAddress)
Implement asynchronous versions where possible.  In this case, `UdpClient` implements an asynchronous send method (`await client.SendAsync(response);`).

2023-02-27 20:44 UTC, erikgabbard commented on .gitignore
> +bin/
I feel like the default gitignore template for Visual Studio should be used instead of a hand written version.

2023-02-27 20:44 UTC, erikgabbard commented on Program.cs
> +IHost host = Host.CreateDefaultBuilder(args)
This can be "shortened" to:
```
Host.CreateDefaultBuilder(args)
    .ConfigureLogging(logger =>
    {
        logger.AddConsole();
    })
    .ConfigureServices(services =>
    {
        services.AddSingleton<IUdpDataHandler, BoxwriterUDPHandler>();
        services.AddSingleton<ITCPDataHandler, BoxwriterTCPHandler>();
        services.AddHostedService<BoxwriterUDPWorker>();
        services.AddHostedService<BoxwriterTCPWorker>();
    })
    .Build()
    .Run();
```

2023-02-27 20:44 UTC, erikgabbard commented on TCP/BoxwriterTCPWorker.cs
> +    protected override async Task StartListeningAsync(IPAddress address, CancellationToken stoppingToken)
Consider just naming these methods `ListenAsync` because they both start and stop.  Alternatively, you might want to create a `StopAsync` method to be available to call in exception handlers, etc.

2023-02-27 20:49 UTC, erikgabbard reviewed
Good job using structured logging!

2023-02-28 19:05 UTC, Gishe commented on TCP/BoxwriterTCPWorker.cs
> +        TcpListener? server = null;
I did this to ensure that if the object is created at all in the finally we close it down to release the port.  This was how every example I looked at handled this including the Microsoft documentation.

2023-02-28 19:08 UTC, Gishe commented on .gitignore
> +bin/
Not using Visual studio so it was the default from Rider.

2023-02-28 19:30 UTC, Drise13 commented on UDP/BoxwriterUDPHandler.cs
> +            var response = Encoding.ASCII.GetBytes($"{{Locate BoxWriter, {ipAddress}, 2202, {Dns.GetHostName()}}}");
Is this response string some sort of magic format? Do we have any documentation on the required layout of the response?

2023-02-28 19:32 UTC, Drise13 approved these changes

2023-02-28 19:44 UTC, agehrin50 approved these changes

2023-02-28 19:57 UTC, erikgabbard approved these changes

2023-02-28 19:59 UTC, merged