Usp 4307 implement the add lines command
ITWDiagraph/BoxwriterInterop pull request #14
Opened 2023-03-17 16:09 UTC by agehrin50

2023-03-17 16:36 UTC, erikgabbard approved these changes

2023-03-17 17:11 UTC, Drise13 requested changes

2023-03-17 17:11 UTC, Drise13 commented on Constants.cs
> +    public const string TokenSeparator = ",";
This is a breaking change

2023-03-17 17:11 UTC, Drise13 commented on Constants.cs
> +    public const string TokenSeparator = ",";
Might want to add a comment that the space is requried

2023-03-17 17:11 UTC, Drise13 commented on Handlers/AddLineCommandHandler.cs
> +            ? new StringResponse(AddLine, printerId, false)
ternary format

2023-03-17 17:11 UTC, Drise13 commented on PrinterConnections.json
Should be git ignored, not commited

2023-03-20 14:54 UTC, erikgabbard commented on Constants.cs
> +    public const string TokenSeparator = ",";
The space should not be required.

2023-03-20 15:04 UTC, erikgabbard commented on PrinterConnections.json
Why would you ignore this and not commit it to the repo? It is a required file for things to work.

2023-03-20 16:16 UTC, erikgabbard commented on Constants.cs
> +    public const string TokenSeparator = ",";
I guess that's fair enough.

2023-03-20 16:17 UTC, erikgabbard commented on PrinterConnections.json
It's true that we don't want our own printers, but you can't exclude the file altoghther.

2023-03-20 19:24 UTC, Drise13 commented on PrinterConnections.json
@agehrin50 This conversation is not resolved. _Something_ should be done about including development settings in the repository, but I'm not 100% clear on the correct course of action. Does this file auto-generate? @Gishe How do we handle this correctly?

2023-03-20 19:45 UTC, erikgabbard commented on PrinterConnections.json
@Drise13 What is your actual objection here?  There is nothing sensitive about including a printer name and IP address from our development environment in the repository as an example of what would appear in the file.  The only thing you don't want to commit to a repo is secret info like username and password.

2023-03-21 17:29 UTC, Gishe requested changes
Please add the example file to the Zip output from the Git action.

2023-03-21 17:29 UTC, Gishe commented on BoxwriterResmarkInterop/Handlers/AddLineCommandHandler.cs
> +        return _printerConnections.Printers.Any(p => p.PrinterId == printerId)
This does not allow users to update the value if it changes.  I would expect calling it with an existing value would update the value not give me a false back.

2023-03-21 17:35 UTC, agehrin50 commented on Configuration/PrinterConnectionInfo.cs
> +public class PrinterConnectionInfo
We now have a class that includes a list of `PrinterConnectionInfo` called `PrinterConnections`

2023-03-21 17:36 UTC, agehrin50 commented on BoxwriterResmarkInterop/Handlers/AddLineCommandHandler.cs
> +        return _printerConnections.Printers.Any(p => p.PrinterId == printerId)
I can update that if that is the expectation. My expectation was that calling it with an existing value would not modify the list of connections

2023-03-21 17:39 UTC, Drise13 commented on BoxwriterResmarkInterop/Handlers/AddLineCommandHandler.cs
> +        return _printerConnections.Printers.Any(p => p.PrinterId == printerId)
I would expect it to replace it with new IP data.

2023-03-22 20:48 UTC, Drise13 approved these changes

2023-03-22 20:55 UTC, merged