USP-4317 add unit tests for Get/Set user elements handlers
ITWDiagraph/BoxwriterInterop pull request #18
Opened 2023-03-20 21:06 UTC by Drise13

2023-03-20 21:43 UTC, erikgabbard requested changes

2023-03-20 21:43 UTC, erikgabbard commented on BoxwriterInterop.Tests/GetUserElementsRequestHandlerTests.cs
> +    public async Task GetUserElements_HandleGoodRequest_ReturnsValidStringResponse()
I feel like this should be a `[Theory]` that tests for different inputs.  I also feel like we are missing a test for invalid or malformed inputs over just throw when no data.

2023-03-20 21:43 UTC, erikgabbard commented on BoxwriterInterop.Tests/SetUserElementsRequestHandlerTests.cs
> +    private static bool IsValidSerializedDictionary(string value)
I'm ok with using the serializer to create the complex string data but we need to be very careful creating methods that themselves should be unit tested.  In this case, we can assume that the out-of-the-box serializer works as intended and provides predictable output.  The `IsValidSerializedDictionary(string value)` method creates a situation where unknown input is compared to pseudo hardcoded data and that interaction needs unit tested.

2023-03-20 21:43 UTC, erikgabbard commented on BoxwriterInterop.Tests/SetUserElementsRequestHandlerTests.cs
> +    public async Task SetUserElements_HandleGoodRequest_ReturnsValidStringResponse()
This test should be a 'Theory` and check that multiple inputs result in the correct corresponding outputs.

2023-03-21 17:41 UTC, Gishe requested changes

2023-03-21 17:41 UTC, Gishe commented on BoxwriterInterop.Tests/GetUserElementsRequestHandlerTests.cs
> +        _mocker.GetMock<IOPCUAService>().Setup(service => service.CallMethodAsync(
This should be in the test that it is used by not in the ctor.  Setting up something in the ctor like this is not recommended and a sign that something should be redesigned to be easier to unit test.

2023-03-21 17:41 UTC, Gishe commented on BoxwriterInterop.Tests/GetUserElementsRequestHandlerTests.cs
> +    private readonly AutoMocker _mocker = new();
I think  you should be setting up your mocker in each configuration otherwise you may get unit tests working and not working depending on if they were run in the same context or separate ones.

2023-03-21 17:41 UTC, Gishe commented on BoxwriterInterop.Tests/SetUserElementsRequestHandlerTests.cs
> +    private readonly AutoMocker _mocker = new();
See my comment above.

2023-03-21 17:41 UTC, Gishe commented on BoxwriterInterop.Tests/SetUserElementsRequestHandlerTests.cs
> +    private const string InvalidRequest = "{Set user elements, 0000, Test Prompt 1, Test Value 1, Test Prompt 2}";
I would be more specific about what kind of invalid request this is.  Something like InvalidRequestNonMatchingPairs.

2023-03-21 17:49 UTC, Drise13 commented on BoxwriterInterop.Tests/GetUserElementsRequestHandlerTests.cs
> +        _mocker.GetMock<IOPCUAService>().Setup(service => service.CallMethodAsync(
That's not according to several parts of documentation and examples that I looked at when doing this work. I read several examples that instructed setting up your common cases available for the entire test class and override them in the places you need specific behavior.

What needs to be re-designed here? How is this a sign of something being hard to unit test?

Setting up a mock is not trivial, sure, but this is the leg work required to do it.

2023-03-22 14:25 UTC, erikgabbard requested changes

2023-03-22 14:25 UTC, erikgabbard commented on BoxwriterInterop.Tests/GetUserElementsRequestHandlerTests.cs
> +        var response = await handler.Handle(new GetUserElementsRequest(ValidRequest), CancellationToken.None);
Consider renaming `response` to `actual`.

2023-03-22 14:25 UTC, erikgabbard commented on BoxwriterInterop.Tests/GetUserElementsRequestHandlerTests.cs
> +        Assert.Equal("{Get user elements, 0000, Test Prompt 1, Test Value 1, Test Prompt 2, Test Value 2}", response.Data);
Ideally `"{Get user elements, 0000, Test Prompt 1, Test Value 1, Test Prompt 2, Test Value 2}"` should be passed in as the `expected` argument with a matching `request` argument as defined by a `Theory`

2023-03-22 14:25 UTC, erikgabbard commented on BoxwriterInterop.Tests/SetUserElementsRequestHandlerTests.cs
> +        var data = SetUserElementsCommandHandler.GetDataAsDictionary(ValidRequest);
Same comment about renaming this to `actual`.

2023-03-22 14:25 UTC, erikgabbard commented on BoxwriterInterop.Tests/SetUserElementsRequestHandlerTests.cs
> +        Assert.Equivalent(new Dictionary<string, string>
Consider extracting your hardcoded dictionary to a variable called `expected`.

2023-03-22 14:25 UTC, erikgabbard commented on BoxwriterInterop.Tests/SetUserElementsRequestHandlerTests.cs
> +        Assert.Equal("{Get user elements, 0000, 2}", response.Data);
Consider extracting `"{Get user elements, 0000, 2}"` to `expected` variable and `response.Data` to `actual` variable.

2023-03-22 15:37 UTC, Drise13 commented on BoxwriterInterop.Tests/GetUserElementsRequestHandlerTests.cs
> +        Assert.Equal("{Get user elements, 0000, Test Prompt 1, Test Value 1, Test Prompt 2, Test Value 2}", response.Data);
That's a refactor if/when these tests become more complicated / more depth. I plan on leaving this as is for now.

2023-03-22 16:34 UTC, Drise13 commented on BoxwriterInterop.Tests/GetUserElementsRequestHandlerTests.cs
> +        var response = await handler.Handle(new GetUserElementsRequest(ValidRequest), CancellationToken.None);
After doing one of these refactors, it felt kinda silly to have every assert statement be 

```
Assert.Equal(expected, actual);
```

I feel like this defeated the purpose of the assert statement specifying exactly what it was testing for by abstracting it away to another location.

2023-03-22 16:37 UTC, erikgabbard commented on BoxwriterInterop.Tests/GetUserElementsRequestHandlerTests.cs
> +        var response = await handler.Handle(new GetUserElementsRequest(ValidRequest), CancellationToken.None);
The names `expected` and `actual` are what are used by convention.

2023-03-22 16:47 UTC, erikgabbard requested changes
None of my concerns have been adequately addressed and all of the comments have just summarily dismissed as "don't want to".

2023-03-22 18:32 UTC, Gishe approved these changes

2023-03-22 18:32 UTC, Gishe commented on BoxwriterInterop.Tests/GetUserElementsRequestHandlerTests.cs
> +    private readonly AutoMocker _mocker = new();
Not creating a new mocker for each test means that mocked changes from a previous test could impact the current test.   This can cause unexpected results if you run a single test vs running all the tests.

2023-03-23 16:32 UTC, agehrin50 approved these changes

2023-03-23 17:55 UTC, merged