Update README.md
ITWDiagraph/BoxwriterInterop pull request #19
Opened 2023-03-22 18:55 UTC by agehrin50

2023-03-22 19:31 UTC, Drise13 requested changes
Looking at the rendered output, its a bit hard to pick up the formatting. Italics are generally difficult to read, bold italics even more so.

Look at this example rest API readme and see its much easier to track

https://github.com/bbc/REST-API-example/blob/master/README.md

2023-03-22 19:31 UTC, Drise13 commented on README.md
> +> {Get tasks, **_PrinterName_**, **_TaskName1_**, **_TaskName2_**, ...}
We should clarify that the results will be empty if no files are present.

2023-03-22 19:34 UTC, Drise13 commented on README.md
> +This command is used to print a message
I think the "This X is used..." is over-worded. Can be reduced to "Prints a message". Same idea with other documentation we've done, get to the point, skip any sentence fluff.

2023-03-22 20:34 UTC, Gishe requested changes

2023-03-22 20:34 UTC, Gishe commented on README.md
> +> {Get lines, **_PrinterName1_**, **_PrinterName2_**, ...}
This is not correct this should respond with Add line not Get lines

2023-03-22 20:34 UTC, Gishe commented on README.md
> +- **_PrinterName_**: Name of a printer that is saved
This should be
` **_PrinterName_**: Name of the printer`

2023-03-22 20:34 UTC, Gishe commented on README.md
> +- **_PrinterName_**: Name of a printer that is saved
Same as above since we are not saving the printer name here.

2023-03-23 19:36 UTC, Drise13 commented on README.md
> +This command pauses the current message
Missed this one: Uses old "This command..." style

2023-03-23 19:38 UTC, Drise13 commented on README.md
> +Making a TCP Request on the port *default 2202* with the data
I would move this default port stuff to a "Making a call" section. You dont need to tell me the same port for every command.

Something like

## Making a request
General requests are made on TCP port `2202` (unless otherwise specified) in the format:

    {command, printerID, param1, param2, ...}

It will typically respond in the following format:

    {command, printerID, result1, result2, ...}

2023-03-23 19:38 UTC, Drise13 commented on README.md
> +The application will respond with
I think we can simplify to `Response`

2023-03-23 19:39 UTC, Drise13 commented on README.md
> +Making a TCP Request on the port *default 2202* with the data
I think we can simplify to `Request`

2023-03-23 19:40 UTC, Drise13 commented on README.md
> +Gets all the saved printers
```suggestion
Returns all saved printer connections
```

2023-03-23 19:41 UTC, Drise13 commented on README.md
> +There will be no tasks returned if there are no tasks on the printer
```suggestion
`{Get tasks, PrinterName}` is returned if there are no tasks on the printer
```

2023-03-23 19:45 UTC, erikgabbard approved these changes

2023-03-23 19:45 UTC, Drise13 commented on README.md
> +Gets the variable data available for the current message. It returns no data if there are no variables in the message.
Move "It returns no data if there are no variables in the message." to the Data detail part

2023-03-23 21:41 UTC, agehrin50 commented on README.md
> +The application will respond with
I think this makes it less clear to the reader for what we are doing

2023-03-24 13:21 UTC, Gishe requested changes

2023-03-24 13:21 UTC, Gishe commented on README.md
>  Making a UDP broadcast Request on port 2200 with the data
The organization of this is odd.  The statement above says requests are made with TCP then the first functionality that we present is the only UDP command.  

I think we should organize the UDP command and the TCP commands separate.  The block talking about TCP commands is good I think it should just be below the UDP command which is setup by itself.

2023-03-24 17:16 UTC, Drise13 approved these changes

2023-03-24 18:26 UTC, merged