Correctly handled non-open channels
ITWDiagraph/BoxwriterInterop pull request #24
Opened 2023-03-24 18:49 UTC by Drise13

OPCUA channels are un-usable once in a faulted state. If they time out, you need to make a new channel.

2023-03-24 19:13 UTC, erikgabbard requested changes

2023-03-24 19:13 UTC, erikgabbard commented on BoxwriterResmarkInterop/OPCUA/ResmarkOPCUAService.cs
> +    private async Task<UaTcpSessionChannel> GetSessionChannel(string connectionName)
Why are we not following the same pattern that we use in the printer handlers?

2023-03-24 19:13 UTC, erikgabbard commented on BoxwriterResmarkInterop/OPCUA/ResmarkOPCUAService.cs
> +                await _channelLookup[connectionName].AbortAsync();
I believe that the channel needs to also be closed and set to `null` so that the GC can reclaim it.

2023-03-24 19:43 UTC, Drise13 commented on BoxwriterResmarkInterop/OPCUA/ResmarkOPCUAService.cs
> +    private async Task<UaTcpSessionChannel> GetSessionChannel(string connectionName)
What do you mean? Example?

2023-03-24 19:47 UTC, Drise13 commented on BoxwriterResmarkInterop/OPCUA/ResmarkOPCUAService.cs
> +            if (_channelLookup[connectionName].State == CommunicationState.Opened)
As far as the end result of `GetSessionsChannel` is concerned, any "cached" channel that isn't actively opened is no longer useful, so it needs to make a new one. I could limit it to `Faulted` but that seems over-restrictive. I don't know what OPCUA would do if you try to open a channel thats "opening", see 

```
private async Task<UaTcpSessionChannel> OpenChannel(string printerId, CancellationToken stoppingToken)
{
    var channel = await GetSessionChannel(printerId);

    if (channel.State != CommunicationState.Opened)
    {
        _logger.LogInformation("Attempting to start OPCUA connection..");

        try
        {
            await channel.OpenAsync(stoppingToken);
        }
        catch (Exception ex)
        {
            throw new OPCUACommunicationFailedException($"Channel could not be opened: {ex}");
        }
    }

    _logger.LogInformation("OPCUA connection successful");

    return channel;
}

2023-03-24 19:48 UTC, Drise13 commented on BoxwriterResmarkInterop/OPCUA/ResmarkOPCUAService.cs
> +            if (_channelLookup[connectionName].State == CommunicationState.Opened)
Here we open the channel if its not opened, so the expectation is that `GetSessionChannel` returns either an open channel, or a channel able to be opened.

2023-03-24 19:54 UTC, Drise13 commented on BoxwriterResmarkInterop/OPCUA/ResmarkOPCUAService.cs
> +                await _channelLookup[connectionName].AbortAsync();
The [documentation ](https://github.com/convertersystems/opc-ua-client#getting-started) just uses abort:

```
catch(Exception ex)
{
    await channel.AbortAsync();
    Console.WriteLine(ex.Message);
}
```

I'm not sure what you mean about setting it to null for GC. Overwriting the value stored at `_channelLookup[connectionName]` in a dictionary should release any reference the dictionary holds. Since we are going overwrite it 3 or so lines later, the GC shouldn't be a concern here. Because the channel is specifically tied to the printer name, and not some magic guid, we are effectively guaranteed to overwrite it (or close the app, whichever comes first).

2023-03-24 20:06 UTC, erikgabbard commented on BoxwriterResmarkInterop/OPCUA/ResmarkOPCUAService.cs
> +    private async Task<UaTcpSessionChannel> GetSessionChannel(string connectionName)
I suppose, at the end of the day, it's a minor nitpick.  I will go ahead and approve.

2023-03-24 20:07 UTC, erikgabbard approved these changes

2023-03-27 18:39 UTC, agehrin50 approved these changes

2023-03-27 18:49 UTC, Gishe approved these changes

2023-03-28 13:52 UTC, merged