Added OPCUA service unit tests
ITWDiagraph/BoxwriterInterop pull request #28
Opened 2023-03-27 18:42 UTC by Drise13

I had to do a substantial refactor of the opcua service to better distill it into seperate parts for testing. I actually like the layout here much more than what we had before.

2023-03-27 21:23 UTC, agehrin50 commented on BoxwriterInterop.Tests/OPCUARequestTests.cs
> +    public void GetArgsAsVariant_ReturnsExpectedResult()
Should we have a negative test here?

2023-03-27 21:27 UTC, agehrin50 commented on BoxwriterInterop.Tests/ResmarkOpcuaServiceTests.cs
> +        Assert.Equal($"ns=2;s={method}", callRequest.MethodsToCall?[0]?.MethodId?.ToString());
Might want to consider making this a constant

2023-03-27 21:33 UTC, Drise13 commented on BoxwriterResmarkInterop/BoxwriterResmarkInterop.csproj
> +        <PackageReference Include="ConfigureAwait.Fody" Version="3.3.2">
Yes

2023-03-27 21:34 UTC, Drise13 commented on BoxwriterInterop.Tests/OPCUARequestTests.cs
> +    public void GetArgsAsVariant_ReturnsExpectedResult()
I don't think a negative test brings a lot of value here.

2023-03-28 12:52 UTC, erikgabbard requested changes

2023-03-28 12:52 UTC, erikgabbard commented on BoxwriterInterop.Tests/ResmarkOpcuaServiceTests.cs
> +        Assert.Equal($"ns=2;s={method}", callRequest.MethodsToCall?[0]?.MethodId?.ToString());
In my own work with the OPCUA library, I have come to the conclusion that `"ns=2;s="` seems to be a constant "prefix" for calling an OPCUA method or reading data.  So you may consider makeing that a constant.

2023-03-28 12:52 UTC, erikgabbard commented on BoxwriterResmarkInterop/OPCUA/ResmarkOPCUAService.cs
>              catch (Exception ex)
This isn't technically part of this PR, but catching a general exception for the only purpose of transforming it to a different exception type is bad form because it will truncate the call stack and make debugging the actual problem harder.

2023-03-28 12:52 UTC, erikgabbard commented on BoxwriterResmarkInterop/OPCUA/ResmarkOPCUAService.cs
> +            catch (Exception e)
In general, if all you are doing is logging, you aren't "handling" the exception and it should be handled by the caller.

2023-03-28 14:21 UTC, erikgabbard commented on BoxwriterResmarkInterop/OPCUA/ResmarkOPCUAService.cs
> +        catch (OPCUACommunicationFailedException e)
Very well then.  I'll resolve the comment.

2023-03-28 14:24 UTC, Drise13 commented on BoxwriterInterop.Tests/ResmarkOpcuaServiceTests.cs
> +        Assert.Equal($"ns=2;s={method}", callRequest.MethodsToCall?[0]?.MethodId?.ToString());
I don't really see a lot of value in a constant here. Hiding expected string literals in a constant (for unit tests, specifically) seems like we move critical information away from where it is most relevant and requires a information hunt (and a context switch) to figure out what the expectation is. Just like if I were testing for the length of an array, I wouldn't expect to make a constant for that length:

    ExpectedLengthOfArray = 3

_sometime later in the file, likely off screen_

    Assert.Equal(ExpectedLengthOfArray, result.Length)

Without looking around the file, can you tell me immediately what the expected array length is?
    
In this example, I feel it is much easier to read and understand

    Assert.Equal(3, result.Length)

Here, we know exactly the expectation is a length of 3 without having to hunt around for the constant's definition. It is immediately obvious within the test statement itself what _exactly_ is going on.

Of course, this only generally applies to unit testing. I would 100% agree that these types of constant values are better represented in named constants outside of a unit test context. However, in a unit testing context, I feel that values used by the unit test assertions should be immediately obvious.

2023-03-28 18:48 UTC, Gishe approved these changes

2023-03-29 14:22 UTC, agehrin50 approved these changes

2023-03-29 14:29 UTC, erikgabbard approved these changes

2023-03-29 14:30 UTC, merged