32 add set count function into interop
ITWDiagraph/BoxwriterInterop pull request #34
Opened 2023-05-01 19:25 UTC by agehrin50

2023-05-01 19:33 UTC, agehrin50 commented on BoxwriterResmarkInterop/Handlers/SetCountCommandHandler.cs
> +        UInt64.TryParse(request.Data.ExtractAdditionalParameter(), out var startCount);
This was a pain to figure out. The firmware needs this parameter to be Uint64 or the call fails.

2023-05-02 13:12 UTC, erikgabbard requested changes

2023-05-02 13:12 UTC, erikgabbard commented on BoxwriterResmarkInterop/Handlers/SetCountCommandHandler.cs
> +        UInt64.TryParse(request.Data.ExtractAdditionalParameter(), out var startCount);
Can you not just cast the return from `request.Data.ExtractAdditionalParameter()` like this:
`var startCount = (UInt64)request.Data.ExtractAdditionalParameter();`

2023-05-02 15:28 UTC, agehrin50 commented on BoxwriterResmarkInterop/Handlers/SetCountCommandHandler.cs
> +        UInt64.TryParse(request.Data.ExtractAdditionalParameter(), out var startCount);
![image](https://user-images.githubusercontent.com/34113332/235712823-97abcf36-6260-4857-9b6a-cafb3ac95a21.png)

2023-05-02 16:10 UTC, erikgabbard commented on BoxwriterResmarkInterop/Handlers/SetCountCommandHandler.cs
> +        UInt64.TryParse(request.Data.ExtractAdditionalParameter(), out var startCount);
Maybe just `Convert.ToUInt64(value)`

2023-05-02 16:18 UTC, agehrin50 commented on BoxwriterResmarkInterop/Handlers/SetCountCommandHandler.cs
> +        UInt64.TryParse(request.Data.ExtractAdditionalParameter(), out var startCount);
Yep that worked

2023-05-02 16:22 UTC, erikgabbard approved these changes

2023-05-02 17:41 UTC, Gishe requested changes
Please add a few unit tests against this call.

2023-05-05 17:53 UTC, Drise13 approved these changes

2023-05-05 18:12 UTC, Gishe approved these changes

2023-05-05 18:13 UTC, merged