Added initial architecture and Get tasks command support
ITWDiagraph/BoxwriterInterop pull request #4
Opened 2023-03-08 21:25 UTC by agehrin50

Used a mediator pattern and added OPCUA support

2023-03-08 21:32 UTC, Drise13 requested changes
Fix git ignore for `.vs` files

2023-03-08 21:49 UTC, Drise13 requested changes

2023-03-08 21:49 UTC, Drise13 commented on Interfaces/IOPCUAService.cs
> +    Task<CallMethodResult?[]?> CallMethodAsync(string connectionName, string method, CancellationToken stoppingToken);
`CallMethodResult?[]?` seems odd to me. What are we doing all this nullability for? Why is it an array vs enumerable or something else?

2023-03-08 21:49 UTC, Drise13 commented on OPCUA/OPCUAGetTaskHandler.cs
> +        //Extract printer id
These types of comments _usually_ mean they should be separate functions.

P.S. _I think this should be broken up_

2023-03-08 21:49 UTC, Drise13 commented on OPCUA/OPCUAGetTaskHandler.cs
> +    public async ValueTask<StringResponse> Handle(GetTaskRequest request, CancellationToken cancellationToken)
What is a value task?

2023-03-08 21:49 UTC, Drise13 commented on OPCUA/OPCUAGetTaskHandler.cs
> +        var printerIdRegex = new Regex(@",\s*(.+)\s*}").Match(data);
I love magic regex strings. What is this searching for?

2023-03-08 21:49 UTC, Drise13 commented on OPCUA/OPCUAGetTaskHandler.cs
> +            throw new InvalidDataException($"Unable to find printer ID. Request was {data}.");
We want to throw here? Why not return an empty response?

2023-03-08 21:49 UTC, Drise13 commented on OPCUA/OPCUAGetTaskHandler.cs
> +        var outputArguments = response?[0]?.OutputArguments;
I feel like there is a lot of excess nullability here. Maybe just me. What do you do if any of it is null?

2023-03-08 21:49 UTC, Drise13 commented on OPCUA/OPCUAGetTaskHandler.cs
> +            throw new InvalidDataException();
Exception with no message

2023-03-08 21:49 UTC, Drise13 commented on OPCUA/OPCUAGetTaskHandler.cs
> +        return new StringResponse("{Get tasks, printerId, " + string.Join(',', outputArguments[1].Value as string[] ?? new[] { "No messages" }) + "}");
Can you use string formatting? Or does `{}` make that hard? I'd rather use interpolation than `+`

2023-03-08 21:49 UTC, Drise13 commented on OPCUA/ResmarkOPCUAService.cs
> +                _logger.LogInformation("Attempting to start OPCUA connection..");
logger probably doesnt belong in the try

2023-03-08 21:49 UTC, Drise13 commented on OPCUA/ResmarkOPCUAService.cs
> +            throw new ChannelClosedException();
So why did we catch on line 48 if we are just going to throw down here anyway?

2023-03-08 21:49 UTC, Drise13 commented on OPCUA/ResmarkOPCUAService.cs
> +        var request = new CallMethodRequest
This should be separate from opening the channel. Should have a `GetOpenedChannel` function or similar.

2023-03-08 21:49 UTC, Drise13 commented on OPCUA/ResmarkOPCUAService.cs
> +        if (!serviceResult.HasValue || !StatusCode.IsGood(serviceResult.Value))
Can't you check the nullability instead of `hasvalue`?

2023-03-08 21:49 UTC, Drise13 commented on OPCUA/ResmarkOPCUAService.cs
> +            throw new Exception("OPCUA call failed");
throwing generic exception, generally seems odd for a failed call.

2023-03-08 21:49 UTC, Drise13 commented on OPCUA/ResmarkOPCUAService.cs
> +    //TODO: don't hard code this
address todo

2023-03-08 21:49 UTC, Drise13 commented on OPCUA/ResmarkOPCUAService.cs
> +        string connectionName,
I think this may be a bit silly to have to "know" your connection name. Seems like something the service should internal figure out

2023-03-08 21:49 UTC, Drise13 commented on TCP/BoxwriterTCPHandler.cs
> +        var tcpRequest = request.data switch
this seems a little kludgy to use a switch expression for. more natural to use an if here

2023-03-08 21:49 UTC, Drise13 commented on TCP/BoxwriterTCPHandler.cs
> +public sealed record GetTaskRequest(string data) : IRequest<StringResponse>;
Why do we define multiple sealed records in multiple places in this file?

2023-03-09 16:49 UTC, agehrin50 commented on OPCUA/OPCUAGetTaskHandler.cs
> +            throw new InvalidDataException($"Unable to find printer ID. Request was {data}.");
We should be able to parse the printer id. If we cannot, we should not be able to continue

2023-03-09 16:51 UTC, erikgabbard requested changes
!NeedsWork

2023-03-09 16:51 UTC, erikgabbard commented on OPCUA/OPCUAGetTaskHandler.cs
> +        var printerIdRegex = new Regex(@",\s*(.+)\s*}").Match(data);
Searching for a comma followed by 0 or more spaces followed by one or more characters followed by 0 or more spaces followed by a curly brace.  ", F }" or ",  0060  }"  where the spaces and the dot are a matching group.  

I don't think this does what it is intended to do unless the printer ID can be any string of any size.  I think if we are going to parse out the printer ID using a regex, we should use a more rigorous regex so that we don't get invalid data.

2023-03-09 16:51 UTC, erikgabbard commented on OPCUA/OPCUAGetTaskHandler.cs
> +            _logger.LogError("Unable to find printer ID. Request was {data}", data);
The `{data}` placeholder in the log message should be capitalized.

2023-03-09 16:51 UTC, erikgabbard commented on OPCUA/OPCUAGetTaskHandler.cs
> +        var outputArguments = response?[0]?.OutputArguments;
WTF does `response?[0]?` even mean?  I think a better approach is:

```
if (response is null)
{
    // Do some null handling
}

var outputArguments = response.First()?.OutputArguments ?? throw new IndexOutOfRangeException();
```

2023-03-09 16:51 UTC, erikgabbard commented on OPCUA/OPCUAGetTaskHandler.cs
> +        return new StringResponse("{Get tasks, printerId, " + string.Join(',', outputArguments[1].Value as string[] ?? new[] { "No messages" }) + "}");
It would be preferable to use a `StringBuilder` here.

```

var responseBuilder = new StringBuilder();
responseBuilder.Append("{Get tasks, printerId, ");

if (outputArguments[1].Value is string[] args)
{
    foreach (var arg in outputArguments[1].Value as string[])
    {
        responseBuilder.Append(arg);
    } 
}
else
{
    responseBuilder.Append("No messages");
}

responseBuilder.Append("}");

return new StringResponse(responseBuilder.ToString());
```

2023-03-09 16:51 UTC, erikgabbard commented on OPCUA/OPCUAGetTaskHandler.cs
> +        return new StringResponse("{Get tasks, printerId, " + string.Join(',', outputArguments[1].Value as string[] ?? new[] { "No messages" }) + "}");
More importantly, on lines 44-48, we throw an `InvalidDataException` when `outputArguments` is `null` or the length is greater than 1 and then we are creating a `ResponseString` using the second element of the `outputArguments` array.  I'm not sure this code is reachable.

2023-03-09 16:51 UTC, erikgabbard commented on OPCUA/ResmarkOPCUAService.cs
> +    private ApplicationDescription _applicationDescription =>
This will create a new `ApplicationDescription` object any time you access `_applicationDescription`.  I think you meant to just use the `=` to initialize the private variable instead of `=>` method bodied expression.

2023-03-09 16:51 UTC, erikgabbard commented on OPCUA/ResmarkOPCUAService.cs
> +        string connectionName,
I agree.  I think the connection name should be resolved in the ctor.

2023-03-09 16:51 UTC, erikgabbard commented on TCP/BoxwriterTCPHandler.cs
> +public sealed record GetTaskRequest(string data) : IRequest<StringResponse>;
Please move all public records and classes to their own files.

2023-03-09 16:51 UTC, erikgabbard commented on TCP/BoxwriterTCPHandler.cs
> +public sealed record GetTaskRequest(string data) : IRequest<StringResponse>;
We want `sealed` records and classes when we intend to prevent anyone from creating classes derived from these.

2023-03-09 16:51 UTC, erikgabbard commented on OPCUA/OPCUAGetTaskHandler.cs
> +        var response = await _opcuaService.CallMethodAsync(printerId, "GetStoredMessageList", cancellationToken);
Please add `ConfigureAwait(false)` to these awaited calls.

2023-03-09 16:51 UTC, erikgabbard commented on OPCUA/ResmarkOPCUAService.cs
> +                await channel.OpenAsync(stoppingToken);
Please add `ConfigureAwait(false)` to these awaited calls.

2023-03-09 16:51 UTC, erikgabbard commented on OPCUA/ResmarkOPCUAService.cs
> +        var response = await channel.CallAsync(callRequest, stoppingToken);
Please add `ConfigureAwait(false)` to these awaited calls.

2023-03-09 16:51 UTC, erikgabbard commented on TCP/BoxwriterTCPHandler.cs
> +        return await _mediator.Send(tcpRequest, cancellationToken);
Please add `ConfigureAwait(false)` to these awaited calls.

2023-03-09 16:51 UTC, erikgabbard commented on TCP/BoxwriterTCPWorker.cs
> +        await stream.WriteAsync(response, 0, response.Length, cancellationToken);
Please add `ConfigureAwait(false)` to these awaited calls.

2023-03-09 16:51 UTC, erikgabbard commented on TCP/BoxwriterTCPWorker.cs
> +               var response = await _mediator.Send(new TCPRequest(data), stoppingToken);
Please add `ConfigureAwait(false)` to these awaited calls.

2023-03-09 16:51 UTC, erikgabbard commented on TCP/BoxwriterTCPWorker.cs
> +               await ProcessDataAsync(response.data, stream, stoppingToken);
Please add `ConfigureAwait(false)` to these awaited calls.

2023-03-09 16:54 UTC, agehrin50 commented on OPCUA/OPCUAGetTaskHandler.cs
> +        return new StringResponse("{Get tasks, printerId, " + string.Join(',', outputArguments[1].Value as string[] ?? new[] { "No messages" }) + "}");
The {} makes that hard

2023-03-09 18:26 UTC, agehrin50 commented on OPCUA/OPCUAGetTaskHandler.cs
> +public class OPCUAGetTaskHandler : IRequestHandler<GetTaskRequest, StringResponse>
This class specifically handles the `GetTask` command. I could rename it to be `OCPUAGetTaskCommandHandler`

2023-03-09 20:42 UTC, agehrin50 commented on TCP/BoxwriterTCPHandler.cs
> +        var tcpRequest = request.data switch
We will be adding more cases here when we add more commands.

2023-03-09 20:58 UTC, agehrin50 commented on OPCUA/ResmarkOPCUAService.cs
> +        if (!serviceResult.HasValue || !StatusCode.IsGood(serviceResult.Value))
What is the disadvantage of using `HasValue` here? Also `serviceResult` is of type status code so I think has value makes sense.

2023-03-10 14:47 UTC, Drise13 commented on OPCUA/OPCUAGetTaskHandler.cs
> +        var outputArguments = response?[0]?.OutputArguments;
`response.First()?` should be `OrDefault` otherwise it will throw.

2023-03-10 14:48 UTC, Drise13 commented on OPCUA/OPCUAGetTaskHandler.cs
> +        var outputArguments = response?[0]?.OutputArguments;
Or, if you just want to throw, just let any of this throw on its own instead of doing all this null checking.

2023-03-10 14:50 UTC, Drise13 commented on OPCUA/ResmarkOPCUAService.cs
> +        if (!serviceResult.HasValue || !StatusCode.IsGood(serviceResult.Value))
It's just odd to specifically check `HasValue` when you're doing `?` null checking everywhere else.

2023-03-10 14:52 UTC, Drise13 commented on TCP/BoxwriterTCPHandler.cs
> +public sealed record GetTaskRequest(string data) : IRequest<StringResponse>;
Sure, but why are they scattered around? Should we have a more organized place (some directory) where we hold all of these records, whether they are separate files or whatever?

2023-03-10 20:55 UTC, Gishe requested changes

2023-03-10 20:55 UTC, Gishe commented on OPCUA/GetTaskCommandHandler.cs
> +    private Match ExtractPrinterId(string data)
Why return the regex and not the value?

2023-03-10 21:16 UTC, Drise13 commented on OPCUA/OPCUAGetTaskHandler.cs
> +    public async ValueTask<StringResponse> Handle(GetTaskRequest request, CancellationToken cancellationToken)
Sure, and within that article:

>**Should every new asynchronous API return `ValueTask` / `ValueTask<TResult>`?**
>
> In short, no: the default choice is still Task / Task<TResult>.
> `Task` and `Task<TResult>` are easier to use correctly than are `ValueTask` and `ValueTask<TResult`>, and so unless the performance implications outweigh the usability implications, `Task` / `Task<TResult>` are still preferred. There are also some minor costs associated with returning a `ValueTask<TResult>` instead of a `Task<TResult>`, e.g. in microbenchmarks it’s a bit faster to `await` a `Task<TResult>` than it is to `await` a `ValueTask<TResult>`

I think we should wrap / hide that fact that `Mediator` forces us to use `ValueTask` and return a normal `Task`

2023-03-10 22:22 UTC, agehrin50 commented on OPCUA/OPCUAGetTaskHandler.cs
> +    public async ValueTask<StringResponse> Handle(GetTaskRequest request, CancellationToken cancellationToken)
Solved this by using mediatR

2023-03-13 13:20 UTC, erikgabbard approved these changes

2023-03-13 13:53 UTC, Gishe approved these changes

2023-03-13 13:58 UTC, erikgabbard approved these changes

2023-03-13 16:11 UTC, Drise13 requested changes
I think this was a good second pass. I have some recommendations to make things a little more robust and make it easier to template out the other commands.

2023-03-13 16:15 UTC, Drise13 commented on OPCUA/ResmarkOPCUAService.cs
> +        var results = response.Results ?? throw new OPCUACommunicationFailedException("Results of the call was null ");
Might also to be nice `Results of {CallName} was null`

2023-03-13 16:17 UTC, Drise13 commented
What happens to all of these exceptions? Does it just kill the application? @Gishe Any idea? What restores the app after it crashes?

2023-03-13 16:47 UTC, erikgabbard commented on Program.cs
> +Host.CreateDefaultBuilder(args).ConfigureLogging(logger => { logger.AddConsole(); }).ConfigureServices(services =>
I think I agree with @Drise13.  These host configurations in program.cs should not be condensed to a single line.

2023-03-13 16:56 UTC, agehrin50 commented on OPCUA/GetTaskCommandHandler.cs
> +            _logger.LogError("Output argument is not correct length");
I expect length of two here. I can adapt it to check for that

2023-03-13 19:50 UTC, Drise13 approved these changes

2023-03-13 19:50 UTC, merged