Usp 4288 implement start task command
ITWDiagraph/BoxwriterInterop pull request #6
Opened 2023-03-14 15:38 UTC by agehrin50

2023-03-14 19:19 UTC, Drise13 commented on OPCUA/ResmarkOPCUAService.cs
> +        Variant[]? inputArgs,
There should be a seperate overload of this function that handles input args. Don't force all consumers to pass in empties.

2023-03-14 19:21 UTC, Drise13 commented on StringResponse.cs
> +    private string FormatResponse(string commandName, string? printerId, string responseData)
Why is the id nullable? Why is it not nullable in the caller? Pick one and stick with it (likely not nullable)

2023-03-14 19:28 UTC, Gishe requested changes

2023-03-14 19:28 UTC, Gishe commented on OPCUA/StartTaskCommandHandler.cs
> +        return (StatusCode.IsGood(result.StatusCode) ? 1 : 0).ToString();
You can do 
```csharp
return StatusCode.IsGood(result.StatusCode) ? "1" : "0";
```

2023-03-14 19:28 UTC, Gishe commented on TCP/BoxwriterTCPHandler.cs
> +        object tcpRequest = request.data switch
If you define this like this
```csharp
 IRequest<StringResponse> tcpRequest = request.data switch
```
You don't need to cast it and you lose the nullable warnings.

2023-03-14 19:30 UTC, Gishe commented on OPCUA/StartTaskCommandHandler.cs
> +        var response = await _opcuaService.CallMethodAsync(printerId, OPCUAMethods.PrintStoredMessage.ToString(),
Oh I guess I miss understood the sequence.  We want load task to select and start task to start printing I guess.  Its hard when the system's don't work 100% the same.

2023-03-14 19:31 UTC, erikgabbard requested changes

2023-03-14 19:31 UTC, erikgabbard commented on OPCUA/GetTaskCommandHandler.cs
>          if (response is null)
```suggestion
        if (response is null || response.OutputArguments is null)
        {
            _logger.LogError("Get tasks OPCUA call failed");

            throw new OPCUACommunicationFailedException("Get tasks OPCUA call failed");
        }

        if (response.OutputArguments.Length != ExpectedOutputArgsLength)
        {
            _logger.LogError(
                "Output argument is not correct length. Expected {ExpectedOutputArgsLength}, got {outputArgumentsLength}",
                ExpectedOutputArgsLength, response.OutputArguments.Length);

            throw new InvalidDataException("Output argument is not correct length.");
        }

        return new StringResponse(CommandName, printerId, GetResponseData(response));
```

2023-03-14 19:31 UTC, erikgabbard commented on OPCUA/ResmarkOPCUAService.cs
> +        CancellationToken stoppingToken,
See previous comment about arguments

2023-03-14 19:31 UTC, erikgabbard commented on OPCUA/ResmarkOPCUAService.cs
>          CancellationToken stoppingToken,
See previous comment about arguments

2023-03-14 19:31 UTC, erikgabbard commented on TCP/BoxwriterTCPHandler.cs
> +        object tcpRequest = request.data switch
```suggestion
        return request.data switch
        {
            var data when data.StartsWith("Get") => 
                await _mediator
                    .Send(new GetTasksRequest(data))
                    .ConfigureAwait(false),
            var data when data.StartsWith("Start") => 
                await _mediator
                    .Send(new StartTaskRequest(data))
                    .ConfigureAwait(false),
            _ => throw new InvalidOperationException(),
        };
```

2023-03-14 19:31 UTC, erikgabbard commented on StringResponse.cs
Consider moving this class to .\Responses\StringResponse.cs making the namespace `BoxwriterResmarkInterop.Responses.StringResponse`.

2023-03-14 19:31 UTC, erikgabbard commented on StringResponse.cs
> +    private string FormatResponse(string commandName, string? printerId, string responseData)
```suggestion
    private string FormatResponse(string commandName, string? printerId, string responseData) => 
        $"{StartToken}{string.Join(TokenSeparator, commandName, printerId, responseData)}{EndToken}";
```

2023-03-14 19:39 UTC, Drise13 commented on TCP/BoxwriterTCPHandler.cs
> +        object tcpRequest = request.data switch
```suggestion

        return await _mediator
                    .Send(request.data switch
        {
            var data when data.StartsWith("Get") => new GetTasksRequest(data),
            var data when data.StartsWith("Start") => new StartTaskRequest(data))
            _ => throw new InvalidOperationException(),
        }.ConfigureAwait(false);

```

2023-03-14 19:57 UTC, Gishe commented on TCP/BoxwriterTCPHandler.cs
> +        object tcpRequest = request.data switch
I disagree with both of these.  Getting the `IRequest<StringResponse>` from the switch is much easier to read and edit.

2023-03-14 21:15 UTC, agehrin50 commented on OPCUA/StartTaskCommandHandler.cs
> +        var response = await _opcuaService.CallMethodAsync(printerId, OPCUAMethods.PrintStoredMessage.ToString(),
I updated the ticket to reflect our conversation. Start task is essentially resume printing

2023-03-14 21:18 UTC, Gishe approved these changes

2023-03-15 14:09 UTC, agehrin50 commented on OPCUA/GetTaskCommandHandler.cs
> +            return args.Aggregate((current, arg) => current + TokenSeparator + arg);
Erik and I found that this was not a simple string.join that could be done here. In the spirit of finishing the MVP, we will be leaving it as is.

2023-03-15 16:13 UTC, agehrin50 commented on Extensions/StringExtensions.cs
> +    public static string ExtractMessageName(this string data)
Reworked

2023-03-15 16:44 UTC, erikgabbard requested changes
Be sure to remember `ConfigureAwait(false)` when awaiting.

2023-03-15 16:44 UTC, erikgabbard commented on Handlers/StartTaskCommandHandler.cs
> +    private const int TaskNumber = 1;
Should this go with the other constants?

2023-03-15 16:44 UTC, erikgabbard commented on Handlers/StartTaskCommandHandler.cs
> +            await _opcuaService.CallMethodAsync(printerId, OPCUAMethods.ResumePrinting.ToString(), cancellationToken, TaskNumber);
`ConfigureAwait(false)`

2023-03-15 16:44 UTC, erikgabbard commented on OPCUA/ResmarkOPCUAService.cs
> +        var response = await MakeCallRequest(method, channel, stoppingToken, inputArgs);
`ConfigureAwait(false)`

2023-03-15 16:44 UTC, erikgabbard commented on OPCUA/ResmarkOPCUAService.cs
> +        return await CallMethodAsync(printerId, method, stoppingToken, inputArgs.ToVariantArray());
`ConfigureAwait(false)`

2023-03-15 16:44 UTC, erikgabbard commented on Handlers/GetTasksRequestHandler.cs
> +            cancellationToken);
`ConfigureAwait(false)`

2023-03-15 16:53 UTC, agehrin50 commented on Handlers/StartTaskCommandHandler.cs
> +    private const int TaskNumber = 1;
I would agree

2023-03-15 17:08 UTC, erikgabbard approved these changes

2023-03-15 17:23 UTC, Drise13 approved these changes

2023-03-15 17:26 UTC, merged